name: PR Merge Sync To Walter-Arduino

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  sync:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: walter-modem
          


      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get the commit details
        id: commit
        run: |
          commit_sha=$(jq -r '.pull_request.head.sha' $GITHUB_EVENT_PATH)
          commit_author=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/$commit_sha | jq -r '.commit.author.name')
          echo "commit_author=$commit_author" >> $GITHUB_ENV

      - name: Clone target repository
        run: |
          git clone -b main https://github.com/QuickSpot/walter-arduino target-repo

      - name: Copy files
        run: |
          cp -R walter-modem/walter-modem/src/* target-repo/src/

      - name: Commit and push changes
        continue-on-error: true
        shell: bash
        run: |
          cd target-repo
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Sync from walter-modem-esp-idf on PR merge by ${{ env.commit_author }}"
          git push --force
